
var _Test = [
	{
		name: "Subbu-test",
		feed: [{"id":"Image_1424502087548","value":"/images/product1.png","name":"Image-1"},{"id":"Text_1424502087548","value":"Samsung S19A10N 18.5-Inch Class","name":"Text-1"},{"id":"Text_1424506095690","value":"1200","name":"Text-1"}],
		objects: [{"id":"template","name":"Container","type":"container","props":[{"name":"border","id":"border","value":"none"},{"name":"background","id":"background","value":"lightblue"}]},{"id":"Image_1424502087548","name":"Image-1","type":"image","props":[{"name":"border","id":"border","value":"1px solid #AEAEAE"},{"name":"background","id":"background","value":"#EEE"},{"name":"height","id":"height","value":"121px"},{"name":"width","id":"width","value":"140px"},{"name":"margin","id":"margin","value":"0px"},{"name":"padding","id":"padding","value":"10px"}],"texts":[],"pos":{"left":74.5,"top":11}},{"id":"Text_1424502087548","name":"Text-1","type":"text","props":[{"name":"border","id":"border","value":"1px solid #AEAEAE"},{"name":"background","id":"background","value":"lightgreen"},{"name":"height","id":"height","value":"40px"},{"name":"width","id":"width","value":"270px"},{"name":"margin","id":"margin","value":"0px"},{"name":"padding","id":"padding","value":"10px"},{"name":"font-size","id":"font-size","value":"14px"},{"name":"color","id":"color","value":"#000"}],"texts":[{"name":"Text Suffix","value":"","id":"suffix"},{"name":"Text Prefix","value":"","id":"prefix"}],"pos":{"left":15,"top":146}},{"id":"Button_1424506095690","name":"Button-1","type":"button","props":[{"name":"border","id":"border","value":"1px solid #AEAEAE"},{"name":"background","id":"background","value":"green"},{"name":"height","id":"height","value":"40px"},{"name":"width","id":"width","value":"140px"},{"name":"margin","id":"margin","value":"0px"},{"name":"padding","id":"padding","value":"10px"},{"name":"font-size","id":"font-size","value":"16px"},{"name":"color","id":"color","value":"#FFF"}],"texts":[{"name":"Button Name","value":"Buy Now","id":"button"}],"pos":{"left":150.5,"top":198}},{"id":"Text_1424506095690","name":"Text-1","type":"text","props":[{"name":"border","id":"border","value":"1px solid #AEAEAE"},{"name":"background","id":"background","value":"#FFF"},{"name":"height","id":"height","value":"40px"},{"name":"width","id":"width","value":"140px"},{"name":"margin","id":"margin","value":"0px"},{"name":"padding","id":"padding","value":"10px"},{"name":"font-size","id":"font-size","value":"14px"},{"name":"color","id":"color","value":"#000"}],"texts":[{"name":"Text Suffix","value":"/-","id":"suffix"},{"name":"Text Prefix","value":"Rs.","id":"prefix"}],"pos":{"left":6.5,"top":198}}],
		template: '<!Doctype html><html><head><title>Ad</title></head><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width, initial-scale=1"><link href=\'/bower_components/bootstrap/dist/css/bootstrap.min.css\' rel=\'stylesheet\'><body><style>body{ font-family: "Helvetica Neue",Helvetica,Arial,sans-serif; font-size: 14px; line-height: 1.42857143; color: #333;background-color: #fff; } .temp_300_250 { margin: 10px 10px; width: 300px; height: 250px; overflow: hidden; background-color: #AEAEAE;position: relative; } .component { display: inline-block; overflow: hidden; cursor: pointer; position: absolute !important; } .component img { width: 100%; border: none } .comp-button { text-align: center; }</style><div id="template" class="temp_300_250 ui-droppable" style="border: none; background: rgb(173, 216, 230);"> <div class="component comp-img ui-draggable-handle comp-added ui-draggable" data-type="image" id="Image_1424502087548" style="position: relative; border: 1px solid rgb(174, 174, 174); height: 121px; width: 140px; margin: 0px; padding: 10px; left: 74.5px; top: 11px; background: rgb(238, 238, 238);"> <img id="image" src="{{= args[\'Image_1424502087548\'] }}"> </div><div class="component comp-text ui-draggable-handle comp-added ui-draggable" data-type="text" id="Text_1424502087548" style="position: relative; border: 1px solid rgb(174, 174, 174); height: 40px; width: 270px; margin: 0px; padding: 10px; font-size: 14px; color: rgb(0, 0, 0); left: 15px; top: 146px; background: rgb(144, 238, 144);"> <span id="prefix"></span> <span id="text">{{= args["Text_1424502087548"] }}</span> <span id="suffix"></span> </div><div class="component comp-button ui-draggable-handle comp-added ui-draggable" data-type="button" id="Button_1424506095690" style="position: relative; border: 1px solid rgb(174, 174, 174); height: 40px; width: 140px; margin: 0px; padding: 10px; font-size: 16px; color: rgb(255, 255, 255); left: 150.5px; top: 198px; background: green;"> <span id="button">Buy Now</span> </div><div class="component comp-text ui-draggable-handle comp-added ui-draggable" data-type="text" id="Text_1424506095690" style="position: relative; border: 1px solid rgb(174, 174, 174); height: 40px; width: 140px; margin: 0px; padding: 10px; font-size: 14px; color: rgb(0, 0, 0); left: 6.5px; top: 198px; background: rgb(255, 255, 255);"> <span id="prefix">Rs.</span> <span id="text">{{= args["Text_1424506095690"] }}</span> <span id="suffix">/-</span> </div></div></body></html>'
	}

]
